name: Formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - name: Check formatting
        run: |
          bun run pretty-check || \
          (bun run pretty-print \
          && git --no-pager diff \
          && exit 1)
